name: Setup

runs:
  using: 'composite'
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: actions/cache@v2
      id: workspace-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-workspace-
    - run: yarn install
      shell: bash
